### PR TITLE
fix(build): Import default block icons.

### LINKED ISSUE #1005: Import default icons used by blocks.
- [x] Move block styles into meta.
- [x] Convert default to react-icon names.
- [x] Add default icons used by blocks to as block metadata. 
- [x] Convert block types file to use styles from meta meta.
- [x] Add Label icons as default icons (like `AiOutlineLoading3Quarters`, `AiOutlineExclamationCircle`) 
- [x] Add import of block default icons during build. (buildIcons in build package).
- [x] Change plugin import to import from each package only once

```js
import {
  AiOutlineLoading3Quarters,
  AiOutlineExclamationCircle,
  AiOutlineFire,
} from 'react-icons/ai';

export default {
  AiOutlineLoading3Quarters,
  AiOutlineExclamationCircle,
  AiOutlineFire,
};

```

### PR DESCRIPTION
**Pull request by sah-memela**
Closes #1005 

### What are the changes and their implications?

Default icons used in blocks are now included in the list of icons to be imported and blocks meta has been refactored.

## Checklist

- [ ] Pull request is made to the "develop" branch
- [ ] Tests added
- [ ] Documentation added/updated
- [x] Code has been formatted with Prettier
- [x] Edits from maintainers are allowed

### CODE REVIEW

File: packages/build/src/build/writePluginImports/writeIconImports.js [hunk 1]
```diff
@@ -17,17 +17,14 @@
 import { nunjucksFunction } from '@lowdefy/nunjucks';
 
 const template = `{%- for package in packages -%}
-{%- for icon in package.icons -%}
-import { {{ icon }} } from '{{ package.package }}';
-{% endfor -%}
-{% endfor -%}
+{% if package.icons.length %}import { {% endif %}{%- for icon in package.icons -%}{% if not loop.last -%} {{ icon }}, {% else -%} {{ icon }} } from '{{ package.package }}';
```
Comment (SamTolmay) [inline packages/build/src/build/writePluginImports/writeIconImports.js:20]: Please move `endif`  for the `if package.icons.length` to the end of the block as that will be easier to understand.

**Comment by sah-memela** [comment]
Review comments resolved 👍

**Review by SamTolmay — APPROVED** [review]
