### PR TITLE
fix(blocksAntd): Selector, MultipleSelector search using input value.

### LINKED ISSUE #968: Ability to search using input value from Selector, MultipleSelector.

### PR DESCRIPTION
**Pull request by sah-memela**
Closes #968

### What are the changes and their implications?

The input value from a Selector, MultipleSelector can now be used to in a onSearch event.

## Checklist

- [x] Pull request is made to the "develop" branch
- [ ] Tests added
- [x] Documentation added/updated
- [x] Code has been formatted with Prettier
- [x] Edits from maintainers are allowed

### CODE REVIEW

File: packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.js [hunk 1]
```diff
@@ -103,6 +104,11 @@ const MultipleSelector = ({
                 methods.setValue(val);
                 methods.triggerEvent({ name: 'onChange' });
               }}
+              onSearch={async (inputVal) => {
+                setFetch(true);
+                await methods.triggerEvent({ name: 'onSearch', event: { inputVal } });
```
Comment (SamTolmay) [inline packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.js:109]: @Gervwyk 
Maybe `searchValue` is a better name here?

File: packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.json [hunk 2]
```diff
@@ -233,6 +233,10 @@
         "onChange": {
           "type": "array",
           "description": "Trigger actions when selection is changed."
+        },
+        "onSearch": {
+          "type": "array",
+          "description": "Trigger actions when input is changed. The event object is populated with inputVal which is the input value entered."
```
Comment (Gervwyk) [inline packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.json:239]: "Trigger actions when input is changed. The input value is passed to the _event operator to be used in actions such as search queries."

File: packages/blocks/blocksAntd/src/blocks/Selector/Selector.json [hunk 3]
```diff
@@ -229,7 +229,11 @@
       "properties": {
         "onChange": {
           "type": "array",
-          "description": "Trigger action when selection is changed."
+          "description": "Trigger actions when selection is changed."
+        },
+        "onSearch": {
+          "type": "array",
+          "description": "Trigger actions when input is changed. The event object is populated with inputVal which is the input value entered."
```
Comment (Gervwyk) [inline packages/blocks/blocksAntd/src/blocks/Selector/Selector.json:236]: "Trigger actions when input is changed. The input value is passed to the _event operator to be used in actions such as search queries."

**Review by Gervwyk — APPROVED** [review]

File: packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.js (hunk 1 above)
Comment (Gervwyk) [reply packages/blocks/blocksAntd/src/blocks/MultipleSelector/MultipleSelector.js:109]: I think `onSearch` is more related to the specific event that is triggered. The fact that you search a value is related to the actions that you write for the event.

**Review by SamTolmay — APPROVED** [review]

**Review by SamTolmay — APPROVED** [review]
